// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdGTXBz1X_WLvFGmsv2y8jw81zvWvfKYo',
    appId: '1:313356734721:web:7f37d72befd5a0484b8b00',
    messagingSenderId: '313356734721',
    projectId: 'adminpainelg',
    authDomain: 'adminpainelg.firebaseapp.com',
    storageBucket: 'adminpainelg.appspot.com',
    measurementId: 'G-5TW2RG1QW4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUpzxRHXmuHmtYQzQM2L5CGYQK7q51S2A',
    appId: '1:313356734721:android:e4b6536deeb5fe514b8b00',
    messagingSenderId: '313356734721',
    projectId: 'adminpainelg',
    storageBucket: 'adminpainelg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfWEEp0rw4wwxeMV1acwIi5T7i6idcbiA',
    appId: '1:313356734721:ios:554ef2ef60822a9d4b8b00',
    messagingSenderId: '313356734721',
    projectId: 'adminpainelg',
    storageBucket: 'adminpainelg.appspot.com',
    iosClientId: '313356734721-g4btq13krdj67bgo1bd0rmb785qp4d17.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminpflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfWEEp0rw4wwxeMV1acwIi5T7i6idcbiA',
    appId: '1:313356734721:ios:554ef2ef60822a9d4b8b00',
    messagingSenderId: '313356734721',
    projectId: 'adminpainelg',
    storageBucket: 'adminpainelg.appspot.com',
    iosClientId: '313356734721-g4btq13krdj67bgo1bd0rmb785qp4d17.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminpflutter',
  );
}
